### ISSUE TITLE
Not able to get metrics and port 8002  for metrics is also not accessible

### ISSUE THREAD

**Issue by SriHarsha-Paladugula** [NVIDIA-AI-IOT/tao-toolkit-triton-apps#2]
![Triton-Server-IOT](https://user-images.githubusercontent.com/38833597/129534183-55fcebcf-30f4-4676-af18-7520385272c2.png)

![metrics_mod](https://user-images.githubusercontent.com/38833597/129533662-358856cf-84c7-453f-85fc-42eae44ddf40.png)

Also i see there is no NMS implemented on the people net output can you please guide where to get that?

**Comment by vpraveen-nv** [comment]
This should be fixed on ToT for a while now. Port 8002 has been exposed in the `./start_server.sh`,

**Comment by vpraveen-nv** [comment]
closing as fixed.
