### ISSUE TITLE
will you opensource the code of tao_cv_inference_pipeline_quick_start_vv0.3-ga?

### ISSUE THREAD

**Issue by BobDLA** [NVIDIA-AI-IOT/tao-toolkit-triton-apps#4]
Hi,
   I followed the instruction from  https://docs.nvidia.com/tao/tao-toolkit/text/tao_cv_inf_pipeline/overview.html and seems not all client side code are open source.  It makes difficult to use the tao pipeline sdk. Do you have plan to support more on that SDK?

**Comment by vpraveen-nv** [comment]
Actually that project has been deprecated in lieu of the deepstream samples and will not be maintained any more.
